services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
    depends_on:
      - mongo

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    command: start-dev
    ports:
      - "8890:8080"
    environment:
#      - KC_DB=postgres
#      - KC_DB_URL_HOST=postgres
#      - KC_DB_URL_DATABASE=keycloak
#      - KC_DB_USERNAME=keycloak
#      - KC_DB_PASSWORD=password
#      - KC_DB_SCHEMA=public
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
#    volumes:
#      - keycloak_data:/opt/jboss/keycloak/standalone/data
#    depends_on:
#      - postgres
#    networks:
#      - keycloak_network
#
#  postgres:
#    image: postgres:latest
#    restart: unless-stopped
#    ports:
#      - "5432:5432"
#    command: postgres -c max_connections=200
#    environment:
#      - POSTGRES_DB=keycloak
#      - POSTGRES_USER=keycloak
#      - POSTGRES_PASSWORD=password
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - keycloak_network

volumes:
  mongo_data:
  keycloak_data:
#  postgres_data:

#networks:
#  keycloak_network:
#    driver: bridge
